In [1]:
import pandas as pd

In [2]:
train_df = pd.read_csv(r"C:\Users\Asus\ML_Projects\Machine_Learning_Project_1\housing\artifact\data_ingestion\2022-10-26-10-10-00\ingested_data\train\housing.csv")

In [3]:
train_df

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -121.46     38.52                29.0       3873.0           797.0   
1        -117.23     33.09                 7.0       5320.0           855.0   
2        -119.04     35.37                44.0       1618.0           310.0   
3        -117.13     32.75                24.0       1877.0           519.0   
4        -118.70     34.28                27.0       3536.0           646.0   
...          ...       ...                 ...          ...             ...   
16507    -117.07     33.03                14.0       6665.0          1231.0   
16508    -121.42     38.51                15.0       7901.0          1422.0   
16509    -122.72     38.44                48.0        707.0           166.0   
16510    -122.70     38.31                14.0       3155.0           580.0   
16511    -122.14     39.97                27.0       1079.0           222.0   

       population  households  median_income  median_house_value  \
0          2237.0       706.0         2.1736             72100.0   
1          2015.0       768.0         6.3373            279600.0   
2           667.0       300.0         2.8750             82700.0   
3           898.0       483.0         2.2264            112500.0   
4          1837.0       580.0         4.4964            238300.0   
...           ...         ...            ...                 ...   
16507      2026.0      1001.0         5.0900            268500.0   
16508      4769.0      1418.0         2.8139             90400.0   
16509       458.0       172.0         3.1797            140400.0   
16510      1208.0       501.0         4.1964            258100.0   
16511       625.0       197.0         3.1319             62700.0   

      ocean_proximity  
0              INLAND  
1          NEAR OCEAN  
2              INLAND  
3          NEAR OCEAN  
4           <1H OCEAN  
...               ...  
16507       <1H OCEAN  
16508          INLAND  
16509       <1H OCEAN  
16510       <1H OCEAN  
16511          INLAND  

[16512 rows x 10 columns]

In [4]:
train_df.shape

(16512, 10)

In [5]:
train_df['median_house_value']

0         72100.0
1        279600.0
2         82700.0
3        112500.0
4        238300.0
           ...   
16507    268500.0
16508     90400.0
16509    140400.0
16510    258100.0
16511     62700.0
Name: median_house_value, Length: 16512, dtype: float64

In [6]:
x,y = train_df.drop(columns=['median_house_value']), train_df[['median_house_value']]

In [7]:
x.shape

(16512, 9)

In [8]:
x.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'ocean_proximity'],
      dtype='object')

In [9]:
y.shape

(16512, 1)

In [10]:
y.columns

Index(['median_house_value'], dtype='object')

In [11]:
train_df.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        158
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [12]:
from sklearn.impute import SimpleImputer

In [13]:
simple_imputer = SimpleImputer(strategy="median")

In [14]:
numerical_columns = x.drop(columns='ocean_proximity')

In [15]:
simple_imputer.fit_transform(numerical_columns)

array([[-1.2146e+02,  3.8520e+01,  2.9000e+01, ...,  2.2370e+03,
         7.0600e+02,  2.1736e+00],
       [-1.1723e+02,  3.3090e+01,  7.0000e+00, ...,  2.0150e+03,
         7.6800e+02,  6.3373e+00],
       [-1.1904e+02,  3.5370e+01,  4.4000e+01, ...,  6.6700e+02,
         3.0000e+02,  2.8750e+00],
       ...,
       [-1.2272e+02,  3.8440e+01,  4.8000e+01, ...,  4.5800e+02,
         1.7200e+02,  3.1797e+00],
       [-1.2270e+02,  3.8310e+01,  1.4000e+01, ...,  1.2080e+03,
         5.0100e+02,  4.1964e+00],
       [-1.2214e+02,  3.9970e+01,  2.7000e+01, ...,  6.2500e+02,
         1.9700e+02,  3.1319e+00]])

In [16]:
simple_imputer.feature_names_in_

array(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income'],
      dtype=object)

In [17]:
simple_imputer.statistics_

array([-118.51   ,   34.26   ,   29.     , 2119.     ,  433.     ,
       1164.     ,  408.     ,    3.54155])

In [18]:
numerical_columns

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -121.46     38.52                29.0       3873.0           797.0   
1        -117.23     33.09                 7.0       5320.0           855.0   
2        -119.04     35.37                44.0       1618.0           310.0   
3        -117.13     32.75                24.0       1877.0           519.0   
4        -118.70     34.28                27.0       3536.0           646.0   
...          ...       ...                 ...          ...             ...   
16507    -117.07     33.03                14.0       6665.0          1231.0   
16508    -121.42     38.51                15.0       7901.0          1422.0   
16509    -122.72     38.44                48.0        707.0           166.0   
16510    -122.70     38.31                14.0       3155.0           580.0   
16511    -122.14     39.97                27.0       1079.0           222.0   

       population  households  median_income  
0          2237.0       706.0         2.1736  
1          2015.0       768.0         6.3373  
2           667.0       300.0         2.8750  
3           898.0       483.0         2.2264  
4          1837.0       580.0         4.4964  
...           ...         ...            ...  
16507      2026.0      1001.0         5.0900  
16508      4769.0      1418.0         2.8139  
16509       458.0       172.0         3.1797  
16510      1208.0       501.0         4.1964  
16511       625.0       197.0         3.1319  

[16512 rows x 8 columns]

In [19]:
numerical_columns.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income'],
      dtype='object')

In [20]:
from sklearn.base import BaseEstimator, TransformerMixin


class Test(BaseEstimator, TransformerMixin):
    def __init__(self, strategy = "median"):
        self.strategy = strategy
        
    def fit(self, x):
        self.statistic_ = []
        for i  in x.columns:
            self.statistic_.append(x[i].median())
        return self

In [21]:
response = Test().fit(numerical_columns)

In [22]:
response.statistic_

[-118.51, 34.26, 29.0, 2119.0, 433.0, 1164.0, 408.0, 3.54155]

In [23]:
numerical_columns.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income'],
      dtype='object')

In [24]:
COLUMN_TOTAL_ROOMS = "total_rooms"
COLUMN_TOTAL_BEDROOMS = "total_bedrooms"
COLUMN_POPULATION = "population"
COLUMN_HOUSEHOLDS = "households"

In [25]:
import numpy as np

In [50]:
class FeatureGenerator(BaseEstimator, TransformerMixin):
    
    def __init__(self, add_bedroom_per_room=True,
                 total_rooms_ix = 3,
                 total_bedrooms_ix = 4,
                 population_ix = 5,
                 households_ix = 6, columns = None):
        """
        FeatureGenerator Intialization
        add_bedroom_per_room : bool
        total_rooms_ix : int index number of total rooms column
        total_bedrooms_ix : int index number of total bedrooms column
        population_ix : int index number of population column
        households_ix : int index number of household column
        """
        try:
            self.columns = columns
            if self.columns is not None:
                total_rooms_ix = self.columns.index[COLUMN_TOTAL_ROOMS]
                total_bedrooms_ix = self.columns.index[COLUMN_TOTAL_BEDROOMS]
                population_ix = self.columns.index[COLUMN_POPULATION]
                households_ix = self.columns.index[COLUMN_HOUSEHOLDS]
            
            self.add_bedroom_per_room = add_bedroom_per_room
            self.total_rooms_ix = total_rooms_ix
            self.total_bedrooms_ix = total_bedrooms_ix
            self.population_ix = population_ix
            self.households_ix = households_ix
        except Exception as e:
            raise e
        
    def fit(self, X, y = None):
        return self
    
    def transform(self, X, y = None):
        try:
            room_per_household = X[:, self.total_rooms_ix] / \
                X[:, self.households_ix]
            population_per_household = X[:, self.population_ix] / \
                X[:, self.households_ix]
            
            if self.add_bedroom_per_room :
                bedrooms_per_room = X[:, self.total_bedrooms_ix] / \
                    X[:, self.total_rooms_ix]
                generated_feature = np.c_[X, room_per_household, population_per_household, bedrooms_per_room]
            
            else:
                generated_feature = np.c_[X, room_per_household, population_per_household]
        
            return generated_feature
        except Exception as e:
            raise e
        

In [51]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

In [52]:
from sklearn.preprocessing import StandardScaler

In [53]:
from numpy.lib.function_base import median


num_pipeline =  Pipeline(steps=[
    ('imputer', SimpleImputer(strategy="median")),
    ('feature_generator', FeatureGenerator()),
    ('scaling', StandardScaler(with_mean=False))
])

In [54]:
from sklearn.preprocessing import OneHotEncoder

In [55]:
cat_pipeline = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy="most_frequent")),
    ("OneHotEncoder", OneHotEncoder()),
    ('scaling', StandardScaler(with_mean=False))
])

In [56]:
numerical_columns = ['longitude', 'latitude', 'housing_median_age', 'total_rooms',
        'total_bedrooms', 'population', 'households', 'median_income']

In [57]:
cat_columns = ['ocean_proximity']

In [58]:
preprocessing = ColumnTransformer([
    ("num_pipeline", num_pipeline, numerical_columns),
    ("cat_pipeline", cat_pipeline, cat_columns)
])

In [59]:
df = pd.read_csv(r"C:\Users\Asus\ML_Projects\Machine_Learning_Project_1\housing\artifact\data_ingestion\2022-10-26-10-10-00\ingested_data\train\housing.csv")

In [60]:
preprocessing.fit_transform(df)

array([[-60.67637885,  18.01769717,   2.30626612, ...,   0.        ,
          0.        ,   0.        ],
       [-58.56324628,  15.4778193 ,   0.55668493, ...,   0.        ,
          0.        ,   2.9869105 ],
       [-59.46744721,  16.54428736,   3.4991624 , ...,   0.        ,
          0.        ,   0.        ],
       ...,
       [-61.3058226 ,  17.98027724,   3.81726807, ...,   0.        ,
          0.        ,   0.        ],
       [-61.29583143,  17.91946985,   1.11336985, ...,   0.        ,
          0.        ,   0.        ],
       [-61.01607865,  18.69593344,   2.14721329, ...,   0.        ,
          0.        ,   0.        ]])

In [62]:
test_df = pd.read_csv(r"C:\Users\Asus\ML_Projects\Machine_Learning_Project_1\housing\artifact\data_ingestion\2022-10-26-10-10-00\ingested_data\test\housing.csv")

In [63]:
preprocessing.fit_transform(test_df)

array([[-58.89591099,  16.03661399,   2.29643557, ...,   0.        ,
          0.        ,   0.        ],
       [-59.9057826 ,  16.39851882,   1.90049841, ...,   0.        ,
          0.        ,   0.        ],
       [-58.92575942,  16.0977148 ,   2.85074761, ...,   0.        ,
          0.        ,   0.        ],
       ...,
       [-59.55755101,  16.187016  ,   3.40505964, ...,   0.        ,
          0.        ,   0.        ],
       [-58.65712362,  15.80631092,   2.37562301, ...,   0.        ,
          0.        ,   0.        ],
       [-58.98048152,  16.06951443,   2.85074761, ...,   0.        ,
          0.        ,   0.        ]])

In [65]:
import dill

In [66]:
with open("processing.pkl", "wb") as prep_object:
    dill.dump(preprocessing, prep_object)

In [68]:
with open('processing.pkl', 'rb') as prep_object:
    preprocessing_loaded_obj = dill.load(prep_object)

In [70]:
preprocessing_loaded_obj.fit_transform(test_df)

array([[-58.89591099,  16.03661399,   2.29643557, ...,   0.        ,
          0.        ,   0.        ],
       [-59.9057826 ,  16.39851882,   1.90049841, ...,   0.        ,
          0.        ,   0.        ],
       [-58.92575942,  16.0977148 ,   2.85074761, ...,   0.        ,
          0.        ,   0.        ],
       ...,
       [-59.55755101,  16.187016  ,   3.40505964, ...,   0.        ,
          0.        ,   0.        ],
       [-58.65712362,  15.80631092,   2.37562301, ...,   0.        ,
          0.        ,   0.        ],
       [-58.98048152,  16.06951443,   2.85074761, ...,   0.        ,
          0.        ,   0.        ]])